### ISSUE TITLE
Close button doesn't work in latest beta 2.1.0 (127)

### ISSUE THREAD

**Issue by JacksonCampbell99** [isontic/Specter#10]
**Describe the bug**
Close button doesn't do anything. Right-clicking the app in the taskbar and clicking close also doesn't work. To close the app I have to click "End task" in Task Manager.

**Operating System**: Windows 11
**Operating System version**: 23H2
**Specter version and build number**: 2.1.0 (127)
**Reproducible:** Every time

**Comment by edeuss** [comment]
@JacksonCampbell99 Yea I know about it, weird flutter issue I am trying to figure out.
