### ISSUE TITLE
Scrolling down top charts doesn't work correctly on Mac

### ISSUE THREAD

**Issue by ManiaMelon** [isontic/Specter#3]
**Describe the bug**
I am experiencing a scrolling bug on mac. No matter where inside the app I try to scroll - the page just jumps back to top, I attached a video down below showing the bug in action! 

**Steps to reproduce**

1. Open Specter
2. Click on 'Top Charts -> Your Charts' and 'Top Charts -> Global Charts'
3. Try scrolling down

**Operating System**: macos Big Sur 11.5.2 (20G95).
**Operating System version**: 11.5.2 (20G95)
**Specter version and build number**: Version 1.4.4 (123)
**Reproducible:** It is reproducible in 99% of the time, it worked as intended once and went back to being broken after navigating to a different area

**Expected behavior**
Expected behaviour would be to be able to scroll down

**Video URL**
https://streamable.com/0xj9dg

**Additional context**
I am using a MacBook Air M1 2020, I am trying to scroll using the built-in trackpad - I would also be delighted if you could integrate a scroll bar, so if something like that happens one could still use it to scroll down! 

Thank you for all your work developing Specter, I enjoy being able to access my stats.fm Account on my Mac, if this bug gets fixed it will be close to perfect!!

**Comment by edeuss** [comment]
@ManiaMelon Thank you for the report, can you try out the beta version on Testflight and see if you are still having that issue? [Beta Link](https://specter.stats.fm/beta)

**Comment by ManiaMelon** [comment]
@edeuss thank you for getting back at me that quickly! I will update my OS to macos 12 today or tomorrow and get back at your right away (testflight isn't supported on macos 11.5.2 anymore.. (gotta love apple for doing shit like that) 
If you want me to, I can delay updating my macos until you can send me a version I can test on 11.5.2 to ensure other people don't encounter the same problem!
How would you like me to proceed?

**Comment by edeuss** [comment]
@ManiaMelon I just realized that the current Testflight version is the same as the App Store version currently.

Are you on the stats.fm Discord? I will announce a Specter 2.0 macOS Alpha in a day or two.

**Comment by ManiaMelon** [comment]
@edeuss just joined, the join link on the main stats.fm website seems to be broken but I managed to find a working one in the support docs, my ID is: zzy#5388

**Comment by edeuss** [comment]
@ManiaMelon The beta is now out [https://specter.stats.fm/beta](https://specter.stats.fm/beta/)
