### ISSUE TITLE
Specter keeps logging me out

### ISSUE THREAD

**Issue by Jakub-Horacek** [isontic/Specter#4]
**Describe the bug**
I keep the Specter app closed but almost everytime in a while when I open this app it wants me to login to my Spotify account.

**Steps to reproduce**
Dont know if this can be easily reproduced

1. Try closing the App (⌘+Q on MacOS / Alt + F4 on Windows)
2. Dont use the app for a few days
3. Open the app again
4. See if you are logged out of your spotify account

**Operating System**: Both - MacOS and Windows
**Operating System version**: Windows 11 22H2 and MacOS 12.6
**Specter version and build number**: Version 1.4.4 (123)
**Reproducible:** I think it is random

**Expected behavior**
I want to be logged in until I log out manually

**Comment by edeuss** [comment]
@Jakub-Horacek Can you try the 2.0 beta? [Beta](https://specter.stats.fm/beta)

**Comment by edeuss** [comment]
@Jakub-Horacek Does the beta fix your issue?

**Comment by Jakub-Horacek** [comment]
> @Jakub-Horacek Does the beta fix your issue?

Haven't encountered it yet so yeah, i think so
